// spa/angular-universal-minimal/src/app/pages/basic/basic.component.ts
import { Component, Input } from '@angular/core';
import { EditableArea } from '@magnolia/angular-editor';

@Component({
  templateUrl: './basic.component.html',
  styleUrls: ['./basic.component.scss'],
  standalone: true,
  imports: [EditableArea]
})
export class BasicComponent {
  @Input() title: any;

  @Input() main: any;
  @Input() extras: any;
  // metadata
  @Input() metadata: any;
}

// spa/vue-minimal/src/pages/Basic.vue
<template>
  <div class="Basic">
    <div class="hint">[Basic.vue]</div>
    <h1>{{ title || metadata['@name'] }}</h1>

    <main>
      <div class="hint">[Main Area]</div>
      <EditableArea v-if="main" v-bind:content="main" />
    </main>

    <div class="Extras">
      <div class="hint">[Extras Area]</div>
      <EditableArea v-if="extras" v-bind:content="extras" />
    </div>
  </div>
</template>

<script>
import { EditableArea } from '@magnolia/vue-editor';

export default {
  name: 'Basic',
  components: {
    EditableArea
  },
  props: ['title', 'metadata', 'main', 'extras']
};
</script>
